swagger:
  enabled: false
  pathMapping: /prod-api

ruoyi:
  profile: ${RUOYI_VOLUNTARY_UPLOAD_PATH:/app/uploadPath}

spring:
  redis:
    host: ${RUOYI_VOLUNTARY_REDIS_HOST:localhost}
    port: ${RUOYI_VOLUNTARY_REDIS_PORT:6379}
    database: ${RUOYI_VOLUNTARY_REDIS_DATABASE:6}
    password: ${RUOYI_VOLUNTARY_REDIS_PASSWORD:}
    timeout: 10s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: ${RUOYI_VOLUNTARY_DB_URL:jdbc:mysql://localhost:3306/ruoyi_voluntary?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true}
        username: ${RUOYI_VOLUNTARY_DB_USER:root}
        password: ${RUOYI_VOLUNTARY_DB_PASSWORD:}
      slave:
        enabled: false
        url:
        username:
        password:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      connectTimeout: 30000
      socketTimeout: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username: ${RUOYI_VOLUNTARY_DRUID_USER:ruoyi}
        login-password: ${RUOYI_VOLUNTARY_DRUID_PASSWORD:123456}
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
